name: Create android development build

on:
  workflow_dispatch:

jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: development