export const PANEL_CONTAINER_ID = "panelID";
export const BADGE_CONTAINER_ID = "badge";
export const EARLIEST_FILTER_SINCE = 1716736622;

export const WAIT_FOR_KIND_ZERO_TIMEOUT_SECONDS = 5;

export const DELAY_AFTER_PROCESSING_EVENT_MS = 10;

export const SUBSCRIPTIONS_MAX_AGE_IN_MINUTES = 60;
